"""A learned scam-screening skill. Yours: read it, edit it, keep it.

Each rule is (what it looks for, kind, pattern, weight, spam_hits,
ham_hits) -- the hits are the training evidence it earned its weight
with. Positive weights accuse; negative weights vouch. A message is
flagged when the summed weights of fired rules reach THRESHOLD.

Learned 2026-08-30 from 4459 UCI SMS + 32 Indian seed examples, on CPU, in under a second.
"""

RULES = [
    ('contains a web link',
     'regex', 'https?://|www\\.|\\b\\w+\\.(?:xyz|shop|info|co|net|org|in|com|apk)\\b', 1, 114, 12),
    ('contains a phone number to call',
     'regex', '\\b(?:\\+?\\d[\\d\\s-]{8,12}\\d)\\b', 3, 318, 3),
    ('contains an SMS shortcode to text',
     'regex', '\\b(?:text|txt|sms|send)\\s+\\w{1,10}\\s+to\\s+\\d{4,6}\\b', 3, 107, 0),
    ('quotes a large money amount',
     'regex', '(?:rs\\.?|inr|₹|\\$|usd|£)\\s?\\d[\\d,]{3,}|\\b\\d+\\s*(?:lakh|crore)\\b', 2, 88, 2),
    ('reads like a personal message to someone known',
     'regex', '\\b(?:bhai|yaar|beta|mummy|papa|didi|bro|dear \\w+,|kal|aaj (?:ka|gym)|good morning|happy birthday|see you|meeting|class)\\b', -2, 1, 145),
    ("contains the word 'but'",
     'word', 'but', -1, 6, 339),
    ("contains the word 'that'",
     'word', 'that', -1, 21, 391),
    ("contains the word 'not'",
     'word', 'not', -1, 19, 320),
    ("contains the word 'can'",
     'word', 'can', -1, 25, 330),
    ("contains the word 'how'",
     'word', 'how', -1, 5, 238),
    ("contains the word 'come'",
     'word', 'come', -1, 2, 185),
    ("contains the word 'when'",
     'word', 'when', -1, 11, 214),
    ("contains the word 'got'",
     'word', 'got', -1, 5, 182),
    ("contains the word 'what'",
     'word', 'what', -1, 14, 216),
    ("contains the word 'its'",
     'word', 'its', -1, 4, 164),
    ("contains the word 'then'",
     'word', 'then', -1, 9, 174),
    ("contains the word 'was'",
     'word', 'was', -1, 4, 152),
    ("contains the word 'like'",
     'word', 'like', -1, 12, 176),
    ("contains the word 'know'",
     'word', 'know', -1, 14, 182),
    ("contains the word 'lor'",
     'word', 'lor', -1, 0, 121),
    ("contains the word 'home'",
     'word', 'home', -1, 2, 128),
    ("contains the word 'going'",
     'word', 'going', -1, 3, 129),
    ("contains the word 'sorry'",
     'word', 'sorry', -1, 2, 117),
    ("contains the word 'there'",
     'word', 'there', -1, 14, 158),
    ("contains the word 'later'",
     'word', 'later', -1, 0, 105),
    ("contains the word 'one'",
     'word', 'one', -1, 6, 127),
    ("contains the word 'love'",
     'word', 'love', -1, 6, 126),
    ("contains the word 'she'",
     'word', 'she', -1, 0, 100),
    ("contains the word 'need'",
     'word', 'need', -1, 6, 121),
    ("contains the word 'still'",
     'word', 'still', -1, 5, 116),
    ("contains the word 'about'",
     'word', 'about', -1, 6, 116),
    ("contains the word 'don'",
     'word', 'don', -1, 7, 116),
    ("contains the word 'much'",
     'word', 'much', -1, 1, 92),
    ("contains the word 'think'",
     'word', 'think', -1, 4, 101),
    ("contains the word 'claim'",
     'word', 'claim', 1, 85, 0),
    ("contains the word 'where'",
     'word', 'where', -1, 1, 88),
    ("contains the word 'hope'",
     'word', 'hope', -1, 4, 97),
    ("contains the word 'hey'",
     'word', 'hey', -1, 1, 85),
    ("contains the word 'some'",
     'word', 'some', -1, 4, 95),
    ("contains the word 'him'",
     'word', 'him', -1, 1, 82),
    ("contains the word 'too'",
     'word', 'too', -1, 1, 81),
    ("contains the word 'here'",
     'word', 'here', -1, 5, 95),
    ("contains the word 'well'",
     'word', 'well', -1, 4, 88),
    ("contains the word 'doing'",
     'word', 'doing', -1, 1, 77),
    ("contains the word 'yeah'",
     'word', 'yeah', -1, 1, 75),
]
THRESHOLD = 1
