"""A learned scam-screening skill. Yours: read it, edit it, keep it.

Each rule is (what it looks for, kind, pattern, weight, spam_hits,
ham_hits) -- the hits are the training evidence it earned its weight
with. Positive weights accuse; negative weights vouch. A message is
flagged when the summed weights of fired rules reach THRESHOLD.

Learned 2026-09-01 from 5574 examples in sms.tsv by `nyaya learn`. Held-out check above threshold was printed at learn time; re-run `nyaya eval` any time.
"""

RULES = [
    ('contains a web link',
     'regex', 'https?://|www\\.|\\b\\w+\\.(?:xyz|shop|info|co|net|org|in|com|apk)\\b', 1, 138, 15),
    ('contains a phone number to call',
     'regex', '\\b(?:\\+?\\d[\\d\\s-]{8,12}\\d)\\b', 3, 407, 2),
    ('contains an SMS shortcode to text',
     'regex', '\\b(?:text|txt|sms|send)\\s+\\w{1,10}\\s+to\\s+\\d{4,6}\\b', 3, 133, 0),
    ('claims the reader won a prize or lottery',
     'regex', '\\b(?:won|winner|congratulat\\w*|lucky draw|lottery|prize|jeeta|jeete)\\b', 1, 129, 21),
    ('asks for a fee, charge or deposit to receive something',
     'regex', '\\b(?:processing fee|registration fee|delivery charge|customs duty|gst fee|verification charge|security deposit|bail amount|advance)\\b', -1, 0, 7),
    ('quotes a large money amount',
     'regex', '(?:rs\\.?|inr|₹|\\$|usd|£)\\s?\\d[\\d,]{3,}|\\b\\d+\\s*(?:lakh|crore)\\b', 3, 97, 0),
    ('reads like a personal message to someone known',
     'regex', '\\b(?:bhai|yaar|beta|mummy|papa|didi|bro|dear \\w+,|kal|aaj (?:ka|gym)|good morning|happy birthday|see you|meeting|class)\\b', -2, 1, 177),
    ("contains the word 'but'",
     'word', 'but', -1, 7, 415),
    ("contains the word 'that'",
     'word', 'that', -1, 26, 486),
    ("contains the word 'not'",
     'word', 'not', -1, 23, 395),
    ("contains the word 'can'",
     'word', 'can', -1, 29, 396),
    ("contains the word 'how'",
     'word', 'how', -1, 7, 286),
    ("contains the word 'when'",
     'word', 'when', -1, 11, 261),
    ("contains the word 'come'",
     'word', 'come', -1, 2, 216),
    ("contains the word 'got'",
     'word', 'got', -1, 7, 223),
    ("contains the word 'what'",
     'word', 'what', -1, 17, 262),
    ("contains the word 'then'",
     'word', 'then', -1, 10, 222),
    ("contains the word 'its'",
     'word', 'its', -1, 6, 204),
    ("contains the word 'like'",
     'word', 'like', -1, 13, 216),
    ("contains the word 'was'",
     'word', 'was', -1, 7, 189),
    ("contains the word 'home'",
     'word', 'home', -1, 2, 163),
    ("contains the word 'lor'",
     'word', 'lor', -1, 0, 145),
    ("contains the word 'going'",
     'word', 'going', -1, 4, 163),
    ("contains the word 'know'",
     'word', 'know', -1, 21, 226),
    ("contains the word 'love'",
     'word', 'love', -1, 8, 170),
    ("contains the word 'there'",
     'word', 'there', -1, 16, 198),
    ("contains the word 'sorry'",
     'word', 'sorry', -1, 3, 148),
    ("contains the word 'later'",
     'word', 'later', -1, 0, 132),
    ("contains the word 'one'",
     'word', 'one', -1, 8, 155),
    ("contains the word 'time'",
     'word', 'time', -1, 19, 191),
    ("contains the word 'still'",
     'word', 'still', -1, 7, 148),
    ("contains the word 'she'",
     'word', 'she', -1, 0, 117),
    ("contains the word 'need'",
     'word', 'need', -1, 9, 153),
    ("contains the word 'about'",
     'word', 'about', -1, 7, 144),
    ("contains the word 'don'",
     'word', 'don', -1, 8, 140),
    ("contains the word 'think'",
     'word', 'think', -1, 4, 125),
    ("contains the word 'claim'",
     'word', 'claim', 1, 108, 0),
    ("contains the word 'much'",
     'word', 'much', -1, 1, 108),
    ("contains the word 'where'",
     'word', 'where', -1, 2, 112),
    ("contains the word 'too'",
     'word', 'too', -1, 1, 106),
    ("contains the word 'some'",
     'word', 'some', -1, 5, 117),
    ("contains the word 'wat'",
     'word', 'wat', -1, 1, 101),
    ("contains the word 'well'",
     'word', 'well', -1, 5, 114),
    ("contains the word 'way'",
     'word', 'way', -1, 1, 97),
    ("contains the word 'hope'",
     'word', 'hope', -1, 4, 108),
    ("contains the word 'him'",
     'word', 'him', -1, 2, 99),
    ("contains the word 'here'",
     'word', 'here', -1, 7, 115),
]
THRESHOLD = 1
